[workspace]
resolver = "3"
members = ["crates/plugins/surrealdb/", "crates/runtime/"]

[workspace.package]
version = "2.2.1"
edition = "2024"
rust-version = "1.95.0"
repository = "https://github.com/Seamlezz/wasmCloud-host"
license = "Unlicense"

[workspace.dependencies]
anyhow = { version = "1", default-features = false }
async-trait = { version = "0.1", default-features = false }
clap = { version = "4", features = ["derive", "env"] }
futures-util = { version = "0.3", default-features = false }
opentelemetry = { version = "0.32", default-features = false, features = ["trace"] }
opentelemetry_sdk = { version = "0.32", default-features = false, features = ["trace"] }
surrealdb = {
  version = "3",
  default-features = false,
  features = ["kv-mem", "protocol-http", "protocol-ws", "rustls"]
}
surrealdb-host-adapter = { git = "https://github.com/Seamlezz/surrealdb-wasi-component", rev = "cb3083c" }
surrealdb-types = "3"
tokio = { version = "1", default-features = false, features = ["full"] }
tracing = {
  version = "0.1",
  default-features = false,
  features = ["attributes"]
}
tracing-opentelemetry = { version = "0.33", default-features = false }
tracing-subscriber = {
  version = "0.3",
  default-features = false,
  features = ["env-filter", "fmt"]
}
wash-runtime = {
  git = "https://github.com/gabber235/wasmCloud",
  rev = "e6ed77a89fb37872420e48097c43b37bc38bdc2f",
  default-features = false,
}
wash = { git = "https://github.com/gabber235/wasmCloud", rev = "e6ed77a89fb37872420e48097c43b37bc38bdc2f", default-features = false, features = ["wasm_component_model_implements"] }
wasmcloud-plugin-surrealdb = { path = "crates/plugins/surrealdb" }
wasmtime = {
  version = "47.0.3",
  default-features = false,
  features = [
    "component-model",
    "component-model-async",
  ]
}
